spring.application.name=careerhub-backend
spring.datasource.url=jdbc:mysql://localhost:3306/careerhub
spring.datasource.username=root
spring.datasource.password=Tushar@2006
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080